[package]
name = "as_traits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
just_prim = { version = "0.1.0" }
align_constr = "0.1.2"